PORTNAME=	lang
PORTVERSION=	22.7.3
CATEGORIES=	sysutils
PKGNAMEPREFIX=	${GH_ACCOUNT}-

MAINTAINER=	franco@pfwsense.org
COMMENT=	PFWsense translations
WWW=		https://translate.pfwsense.org/

LICENSE=	BSD2CLAUSE

USES=		gettext-tools

NO_ARCH=	yes
NO_BUILD=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	${CATEGORIES:[1]}

.include <bsd.port.mk>
